### ISSUE TITLE
Giving M values as input

### ISSUE THREAD

**Issue by MCorentin** [JmWangBio/ComBatMet#1]
Hi, 

Thank you for Combat-Met. I wonder if it would be possible to implement a function that would directly take M values as input ? 

Especially since you already implemented https://github.com/JmWangBio/ComBatMet/blob/main/R/Mvalue_ComBat

Regards,
Corentin

**Comment by JmWangBio** [comment]
Absolutely! I will implement it and let you know once it is ready.

**Comment by JmWangBio** [comment]
Hi @MCorentin - Thank you for pointing this out and taking the time to raise the issue. I have updated ComBat_met and Mvalue_ComBat by allowing both functions to take M-values as input. Note that if you supply M-values as input, the output will also be M-values. Please let me know if this resolves the issue on your end. If there are any further problems, feel free to reopen the issue or raise a new one.
